{
 "title": "Network Gateway",
 "description": "Main dashboard for the network gateway",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{namespace=~\"ng-.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(kube_pod_created{namespace=~\"$namespace\", pod=~\"gateway-api.*\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Write Primaries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ng_aggregator_is_primary_info{namespace=\"$namespace\"}) "
    }
   ]
  },
  {
   "title": "Avg. Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", container=~\"gateway-api|data-aggregator\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Avg. CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sum by (container, name) (rate(container_cpu_usage_seconds_total{container=\"data-aggregator\", namespace=\"$namespace\"}[60s]) * 1024 * 60) / on (container, name) (container_spec_cpu_shares{container=\"data-aggregator\", namespace=\"$namespace\"}) / 60 * 100) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "avg(sum by (container, name) (rate(container_cpu_usage_seconds_total{container=\"gateway-api\", namespace=\"$namespace\"}[60s]) * 1024 * 60) / on (container, name) (container_spec_cpu_shares{container=\"gateway-api\", namespace=\"$namespace\"}) / 60 * 100) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Data Aggregator Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(kube_pod_created{namespace=~\"$namespace\", pod=~\"data-aggregator.*\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "API Reqs In Progress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{namespace=\"$namepace\", container=\"gateway-api\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Avg. Number of Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(process_num_threads{namespace=\"$namespace\", container=~\"gateway-api|data-aggregator\"}) by (container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg .NET allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(dotnet_total_memory_bytes{namespace=\"$namespace\", container=~\"gateway-api|data-aggregator\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "GC Collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(dotnet_collection_count_total{namespace=\"$namespace\", container=~\"gateway-api|data-aggregator\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Data Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Database Connection",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"database_connection_check\", container=\"data-aggregator\"}) / count(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"database_connection_check\", container=\"data-aggregator\"})"
    }
   ]
  },
  {
   "title": "Health Check",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"aggregator_health_check\", container=\"data-aggregator\"}) / count(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"aggregator_health_check\", container=\"data-aggregator\"})"
    }
   ]
  },
  {
   "title": "Time delay between Aggregator and Round Timestamp",
   "type": "timeseries",
   "description": "All three numbers are slightly different numbers to measure.\n\nLag at last commit measures the \"best case\", Lag at last loop start measures the \"current situation\" and \"Peak lag before last commit\" measures the worst case.\n \nA large number here indicates either a delay between network commit and the aggregator ingestion somewhere OR clock drift between the Data Aggregator and Network.",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time((max(ng_ledger_commit_last_commit_timestamp_seconds{namespace=\"$namespace\", container=\"data-aggregator\"} > 0) - max(ng_ledger_commit_tip_round_unix_timestamp_seconds{namespace=\"$namespace\", container=\"data-aggregator\"} > 0))[$__interval:1s])",
     "legendFormat": "Avg lag at last commit"
    },
    {
     "expr": "max(avg_over_time(ng_ledger_commit_peak_round_timestamp_data_aggregator_clock_delay_before_last_commit_seconds{namespace=\"$namespace\", container=\"data-aggregator\"}[$__interval]))",
     "legendFormat": "Avg peak lag before last commit"
    },
    {
     "expr": "max_over_time((max(ng_ledger_commit_last_ledger_extension_attempt_start_timestamp_seconds{namespace=\"$namespace\", container=\"data-aggregator\"} > 0) - max(ng_ledger_commit_tip_round_unix_timestamp_seconds{namespace=\"$namespace\", container=\"data-aggregator\"} > 0))[$__interval:1s])",
     "legendFormat": "Worst case lag in interval"
    }
   ]
  },
  {
   "title": "Ingestion Rate",
   "type": "timeseries",
   "description": "Includes system transactions",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_ledger_commit_committed_transactions_count{namespace=\"$namespace\", container=\"data-aggregator\"}[$__interval])) ",
     "legendFormat": "data-aggregator"
    }
   ]
  },
  {
   "title": "Ledger Batch Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "sum(rate(ng_ledger_commit_batch_commit_time_seconds_count{container=\"data-aggregator\", namespace=\"$namespace\"}[$__interval]))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time since last DB Update",
   "type": "stat",
   "description": "This number includes the time for the metrics to get to Grafana and render the dashboard! A time <10 seconds is expected.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - (max(ng_ledger_commit_last_commit_timestamp_seconds{namespace=\"$namespace\"} > 0) OR (max(max_over_time(ng_ledger_commit_last_commit_timestamp_seconds{namespace=\"$namespace\"}[$__range]) > 0)))"
    }
   ]
  },
  {
   "title": "Synced Up Nodes",
   "type": "stat",
   "description": "The number of nodes which are sufficiently synced up to contribute to calculations on ledger extension.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ng_ledger_sync_sufficiently_synced_up_nodes_total{container=\"data-aggregator\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Nodes to commit",
   "type": "stat",
   "description": "The number of nodes which are sufficiently synced up to contribute to calculations on ledger extension.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ceil(ng_ledger_sync_sufficiently_synced_up_nodes_total{container=\"data-aggregator\", namespace=\"$namespace\"}\n* ng_ledger_sync_trust_weighting_required_for_quorum_total{container=\"data-aggregator\", namespace=\"$namespace\"}\n/ ng_ledger_sync_sufficiently_synced_up_nodes_trust_weighting_total{container=\"data-aggregator\", namespace=\"$namespace\"}\n))"
    }
   ]
  },
  {
   "title": "DB State Version",
   "type": "stat",
   "description": "The number of nodes which are sufficiently synced up to contribute to calculations on ledger extension.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(ng_ledger_commit_tip_state_version{container=\"data-aggregator\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "State Version"
    }
   ]
  },
  {
   "title": "Target Lag",
   "type": "stat",
   "description": "The highest seen target state version across nodes, minus the database state version.\n\nThis can be negative because the Core API can report a target state version less than its ledger tip somehow.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(ng_node_ledger_target_state_version{container=\"data-aggregator\", namespace=\"$namespace\"}[$__interval]))\n- max(max_over_time(ng_ledger_commit_tip_state_version{container=\"data-aggregator\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Node state version vs Gateway DB",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 34 },
   "targets": [
    {
     "expr": "max by (node) (max_over_time(ng_node_ledger_tip_state_version{container=\"data-aggregator\",namespace=\"$namespace\"}[$__interval]))\n- ignoring (node) group_left max(max_over_time(ng_ledger_commit_tip_state_version{container=\"data-aggregator\",namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Worker error count",
   "type": "timeseries",
   "description": "Broken down by worker, node and error.\n(Summed over each interval)",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ng_workers_global_error_count{namespace=\"$namespace\", container=\"data-aggregator\"}[$__interval])) by (worker, error) > 0",
     "legendFormat": "{{worker}} ({{error}})"
    },
    {
     "expr": "sum(increase(ng_workers_node_error_count{namespace=\"$namespace\", container=\"data-aggregator\"}[$__interval])) by (worker, node, error) > 0",
     "legendFormat": "{{node}}: {{worker}} ({{error}})"
    }
   ]
  },
  {
   "title": "P90 transaction batch fetch time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, avg(rate(ng_node_fetch_transaction_batch_time_seconds_bucket{namespace=\"$namespace\", container=\"data-aggregator\"}[5m])) by (le, node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Could commit",
   "type": "status-history",
   "description": "Whether we've been able to commit an extension at the last attempt.\n\nWe take max_over_time in order to report any successful attempt in the period.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "max(max_over_time(ng_ledger_sync_quorum_exists_status{container=\"data-aggregator\",namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Consistency",
   "type": "status-history",
   "description": "If the last agreed extension is self-consistent with itself and the parent in the database (based on transaction hashes and accumulators).\n\nWe take the max over all data aggregators as consistency is marked as unknown at boot-up time.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max(min_over_time(ng_ledger_sync_quorum_extension_consistent_status{container=\"data-aggregator\",namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Inter-Node Consistency Status",
   "type": "status-history",
   "description": "Consistent indicates ledger is consistent with the DB (and/or a majority of other synced up nodes).\nUnknown indicates they might not be synced up (or the data aggregator has just been restarted).\nINCONSISTENT indicates known inconsistent against DB ledger or quorum. This is a critical issue.",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "min(min_over_time(ng_node_ledger_tip_is_consistent_with_quorum_status{container=\"data-aggregator\",namespace=\"$namespace\"}[$__interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"data-aggregator.*\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"data-aggregator.*\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "Gateway API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "RO Database Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"readonly_database_connection_check\", container=\"gateway-api\"}) / count(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"readonly_database_connection_check\", container=\"gateway-api\"})"
    }
   ]
  },
  {
   "title": "RW Database Connection",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"readwrite_database_connection_check\", container=\"gateway-api\"}) / count(aspnetcore_healthcheck_status{namespace=\"$namespace\", name=\"readwrite_database_connection_check\", container=\"gateway-api\"})"
    }
   ]
  },
  {
   "title": "Requests by action",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{namespace=\"$namespace\", container=\"gateway-api\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "P95 response latency by action (in preceding 5 mins)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\", namespace=\"$namespace\", container=\"gateway-api\"}[5m])) by (le, action))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"gateway-api.*\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"gateway-api.*\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Response HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{namespace=\"$namespace\", container=\"gateway-api\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API percentile request latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\", namespace=\"$namespace\", container=\"gateway-api\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\", namespace=\"$namespace\", container=\"gateway-api\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\", namespace=\"$namespace\", container=\"gateway-api\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Top 10 API Errors in Time Period",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(ng_gateway_response_error_count{namespace=\"$namespace\", container=\"gateway-api\"}[$__range])) by (action, status_code, exception, gateway_error) > 0)",
     "legendFormat": "{{action}} {{status_code}} ({{exception}}, {{gateway_error}})"
    }
   ]
  },
  {
   "title": "Delay between Gateway API clock and Round Timestamp",
   "type": "timeseries",
   "description": "A large number here indicates either a delay between network commit and the aggregator ingestion (see graph above), a DB replication delay OR clock drift between the Gateway API/s and Network.",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min(min_over_time(ng_gateway_ledger_tip_round_timestamp_gateway_api_clock_lag_at_last_request_seconds{namespace=\"$namespace\", container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Min delay (across all requests and Gateway APIs)"
    },
    {
     "expr": "max(max_over_time(ng_gateway_ledger_tip_round_timestamp_gateway_api_clock_lag_at_last_request_seconds{namespace=\"$namespace\", container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Max delay (across all requests and Gateway APIs)"
    }
   ]
  },
  {
   "title": "API Error Response Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_gateway_response_error_count{namespace=\"$namespace\", container=\"gateway-api\"}[$__interval])) by (action, status_code, exception, gateway_error) > 0",
     "legendFormat": "{{action}} {{status_code}} ({{exception}}, {{gateway_error}})"
    }
   ]
  },
  {
   "title": "Core APIs -  Gateway Health Check",
   "type": "status-history",
   "description": "Shows the worst status seen across all Gateway APIs",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "min by (node) (ng_node_gateway_health_check_status{container=\"gateway-api\",namespace=\"$namespace\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Healthy Core APIs by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 95 },
   "targets": [
    {
     "expr": "ng_nodes_gateway_health_check_node_statuses{container=\"gateway-api\",namespace=\"$namespace\",status=\"HEALTHY_AND_SYNCED\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lagging Core APIs by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "ng_nodes_gateway_health_check_node_statuses{container=\"gateway-api\",namespace=\"$namespace\",status=\"HEALTHY_BUT_LAGGING\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unhealthy Core APIs by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 95 },
   "targets": [
    {
     "expr": "ng_nodes_gateway_health_check_node_statuses{container=\"gateway-api\",namespace=\"$namespace\",status=\"UNHEALTHY\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mempool and Transaction Submission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 }
  },
  {
   "title": "Resubmission queue",
   "type": "stat",
   "description": "Count of transactions needing resubmission",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ng_db_mempool_transactions_needing_resubmission_total{namespace=\"$namespace\", container=\"data-aggregator\"}) by (container)"
    }
   ]
  },
  {
   "title": "Mempool transaction status changes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 3, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "sum(rate(ng_db_mempool_transactions_added_from_gateway_submission_count{namespace=\"$namespace\", container=\"gateway-api\"}[5m]))",
     "legendFormat": "First submitted to Gateway"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_added_from_node_mempool_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Discovered in node mempool"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_as_missing_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Now missing"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_assumed_in_node_mempool_after_resubmission_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Resubmitted"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_reappeared_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Reappeared"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_as_failed_for_timeout_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Timeout failure"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_failed_from_initial_submission_count{namespace=\"$namespace\", container=\"gateway-api\"}[5m]))",
     "legendFormat": "Failed at submission"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_failed_during_resubmission_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Failed at resubmission"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_resolved_but_unknown_status_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Yet unknown resolution"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_committed_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_committed_which_were_failed_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Committed after failed"
    }
   ]
  },
  {
   "title": "Mempool size by node",
   "type": "timeseries",
   "description": "The mempool union can lag slightly behind individual nodes, as we combine the latest snapshot of the node mempools regularly.\n\nIt also only includes transactions we've managed to read the contents of - we can \"miss\" transactions which leave the mempool before we managed to read their contents.",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "avg(ng_node_mempool_combined_current_size_total{namespace=\"$namespace\",container=\"data-aggregator\"})",
     "legendFormat": "Mempool union across all nodes"
    },
    {
     "expr": "avg(ng_node_mempool_size_total{namespace=\"$namespace\", container=\"data-aggregator\"}) by (node)",
     "legendFormat": "Node: {{node}}"
    }
   ]
  },
  {
   "title": "DB Mempool Transactions table size by status",
   "type": "timeseries",
   "description": "The DB table gets pruned regularly. Committed currently get pruned after a few seconds, Failed/Missing after a week. \n\nExcessive MISSING typically indicates a race condition between non-Gateway Txns being discovered in a mempool and being committed to the DB ledger.",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 104 },
   "targets": [
    {
     "expr": "avg(ng_db_mempool_size_by_status_total{namespace=\"$namespace\", container=\"data-aggregator\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Txn Status Flips [24h]",
   "type": "stat",
   "description": "Count of any pending transactions temporarily marked as failed before being marked as committed in the last 24h. We don't want this to ever happen.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ng_db_mempool_transactions_marked_committed_which_were_failed_count{namespace=\"$namespace\", container=\"data-aggregator\"}[24h])) or vector(0)"
    }
   ]
  },
  {
   "title": "Initial transaction submission node requests",
   "type": "timeseries",
   "description": "The Attempt/Error/Success lines show the request response. The Result: X lines show what happened at initial submission to a node.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_construction_transaction_submission_request_count{namespace=\"$namespace\", container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Attempt"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_submission_error_count{namespace=\"$namespace\", container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_submission_success_count{namespace=\"$namespace\", container=\"gateway-api\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_submission_resolution_count{namespace=\"$namespace\", container=\"gateway-api\"}[5m])) by (result)",
     "legendFormat": "Result: {{result}}"
    }
   ]
  },
  {
   "title": "Transaction resubmission node requests",
   "type": "timeseries",
   "description": "The Attempt/Error/Success lines show the overall status of the resubmission request made to the node. The Result: X lines show a more detailed view by error code.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_attempt_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Attempt"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_error_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_success_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_resolution_count{namespace=\"$namespace\", container=\"data-aggregator\"}[5m])) by (result)",
     "legendFormat": "Result: {{result}}"
    }
   ]
  }
 ]
}