COMPOSE_FILE_OVERIDE = "COMPOSE_FILE_OVERIDE"
NODE_BINARY_OVERIDE = "NODE_BINARY_OVERIDE"
NGINX_BINARY_OVERIDE = "NGINX_BINARY_OVERIDE"

NODE_END_POINT = "NODE_END_POINT"
NODE_HOST_IP_OR_NAME = "NODE_HOST_IP_OR_NAME"
DISABLE_VERSION_CHECK = "DISABLE_VERSION_CHECK"
UNZIPPED_NODE_DIST_FOLDER = "UNZIPPED_NODE_DIST_FOLDER"
APPEND_DEFAULT_CONFIG_OVERIDES = "APPEND_DEFAULT_CONFIG_OVERIDES"

PRINT_REQUEST="PRINT_REQUEST"